# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1loJIqfTr103ZTnwKrbfUPye_l478u_XC
"""

from flask import Flask, render_template, request, jsonify
import requests
import pickle
import numpy as np
import sklearn
from joblib import dump, load
from sklearn.preprocessing import StandardScaler
from joblib import dump, load
app = Flask(__name__)
model = pickle.load(open('ranfor_model.pkl', 'rb'))

@app.route('/')
def Home():
    return render_template('index.html')

@app.route("/predict", methods=['POST'])
def predict():
    
    if request.method == 'POST':
        age = int(request.form['Age'])
        gender=int(request.form['gender'])
        hypertension=int(request.form['hypertension'])
        f_name = request.form['first-name']
        l_name = request.form['last-name']
        
        heart_disease=int(request.form['heart_disease'])
        ever_married=0
    
        work_type=request.form['work_type']
        if(work_type=='Self-employed'):
            work_type=1
        elif(work_type=='Private'):
          work_type=0
        elif(work_type=='Govt_job'):
          work_type=2  
        elif(work_type=='children'):
          work_type=3
        elif(work_type=='Never_worked'):
          work_type=4       

        Residence_type=request.form['Residence_type']
        if(Residence_type=='Urban'):
            Residence_type=0
            
        elif(Residence_type=='Rural'):
          Residence_type=1
        avg_glucose_level=int(request.form['avg_glucose_level']) 
        
        bmi=int(request.form['bmi'])
       
        smoking_status=int(request.form['smoking_status'])
        
        values = [[age,hypertension,heart_disease,Residence_type,avg_glucose_level, bmi,gender,work_type,smoking_status]]
        prediction=model.predict(values)
        result = round(prediction[0], 2)
        if result == 1:
          return render_template('index.html',prediction_text="Hey %s %s As per your entered details, You have been diagnosed with high Stroke Risk. Consult a doctor immediately for accurate diagnosis and early treatment. Take Care :)" %(f_name, l_name))
        elif result == 0:
          return render_template('index.html',prediction_text=" Hey %s %s ,Congrats!! You have maintained your health well. You Are pretty much safe from Stroke." %(f_name, l_name))
        else:
          return render_template('index.html')

if __name__=="__main__":
    app.run(debug=True)

